### ISSUE TITLE
The default import typings are broken

### ISSUE THREAD

**Issue by mkbaranovskyi** [textgears/api-node#2]
The documentation example doesn't work. 

This doesn't work
```js
import textgears from 'textgears-api';

const textgearsApi = textgears(...);
```

This does work but the typings are incorrect, stating that the expression is not callable
```js
import * as textgears from 'textgears-api';

const textgearsApi = textgears(...);
```

**Comment by insbrook** [comment]
Thank you so much for the found bug. I've updated README file accordingly.
